openid_connect:
  name: :openid_connect
  discovery: true
  scope:
    - :openid
    - :email
    - :profile
    - :address
  response_type: :code
  issuer: <%= ENV['OPIDC_CLIENT_ISSUER'] %>
  client_options:
    identifier: <%=  ENV['OPIDC_CLIENT_ID'] %>
    secret: <%= ENV['OPIDC_SECRET_KEY'] %>
    host: <%= ENV['OPIDC_HOST'] %>
    redirect_uri: <%= "#{ENV['OPIDC_REDIRECT_HOST']}/users/auth/openid_connect/callback" %>

oid_prefix:
  Section: '2.16.840.1.113883.3.1502.1'
  Question: '2.16.840.1.113883.3.1502.2'
  ResponseSet: '2.16.840.1.113883.3.1502.3'

elasticsearch:
  log: false

app_version: '1.10-alpha'
disable_user_registration: false
#
# This URL should use the internal cluster name for the concept-manager service.
# If you need this to be resolvable in your local environment, then add an
# alias in your local systems /etc/hosts (or equivalent) file to map this hostname
# to the proper IP address in your environment.
concept_service_url: 'http://concept-manager.sdp.svc:8080'
